### ISSUE TITLE
Settings are not saved upon reboot

### ISSUE THREAD

**Issue by Buster14** [XWolfOverride/DuckDNS#3] opened 2021-01-11 01:29 UTC
Hi, i hope you're still around,
Your client is the only one that works with forcebindip,
the java client wont work
But the settings of your app arent saved upon reboot.
That and i was also wondering if there's any chance you could add feature to bind to specific nic?

**Comment by XWolfOverride** [comment] 2021-02-05 12:05
Hello.
I see that the configuration gets saved only when click on the OK button, but if there is any kind of problem saving it, there is no alert to the user.

As right now i'm adapting some UI changes I will add an autosave feature, and some kind of non blocking configuration save notifications.

For the bind of specific nic did you refer to sending the update singals throught an specific nic or resolving the IP of this nic? take in mind local and remote IPs can be different unless a more advanced network is configured.

**Comment by Buster14** [comment] 2021-02-11 13:30
Hi, sorry i didn't see your reply. 
Regarding the config save, please ignore it i think i forgot to press the OK button.
For binding specific IP, you can see NOIP's windows client, it has option to bind to specific NIC to be used by multi NIC server.
I have tried using a combination of forcebindip with your app. Strangely sometimes it works but sometimes it doesn't
Especially during startup it doesnt work, i run it with this batch command :

`"C:\Program Files\ForceBindIP\ForceBindIP64.exe" -i 192.168.200.200 "C:\DuckDns\Duckdns.exe"`

BTW i'm getting this error sometimes, but on older buiild,
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at DuckDNS.DDns.Update()
   at DuckDNS.Form1.UpdateDNS()
   at DuckDNS.Form1.timer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9044 (WinRelRS5.050727-9000)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
DuckDNS
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/DuckDns/Duckdns.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9038 (WinRelRS5.050727-9000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9042 (WinRelRS5.050727-9000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9031 (WinRelRS5.050727-9000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9046 (WinRelRS5.050727-9000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9031 (WinRelRS5.050727-9000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```
I will try the newer version to see if it resolves it.

**Comment by XWolfOverride** [comment] 2021-02-11 17:20
Hi, I think this "server unavailable" message is here for any kind of network problem. I mean, this error indicates that the DuckDNS.exe application can not connect to the duckdns server, I don't know if there is any kind of problem caused by forcebindip but I think it does nothing. I see in the official forcebindip homepage how this application works and I think it does not work with .net applications, it loads the application without executing it and inject at runtime a modified version of the windows networks dlls that handles the binding, the plrboem here is that the .net exe applications are only small launchers that starts the .net framework calling the non native code in the exe, then it is possible that the process started and injected by forcebindip is not the process running the .net code, and then depending on which interface uses the DuckDNS application for the messaging (load balanced) uses the correct or not.

I will try to "bind" the DuckDNS application to a network interface on next version.

Other problem I see is the error dialog.
Is the error dialog similar to this?
![Error dialog](https://user-images.githubusercontent.com/7501291/107672865-afc85200-6c95-11eb-8d1f-272424a50dcd.jpg)

I don't want the error to be shown this way, other thing to fix.

**Comment by Buster14** [comment] 2021-02-12 00:31
Yes thats what it looks like. 
Ah yes, duckdns is apparently down. 
Happens very rare thats why i didn't think it was the issue. 
Cool, looking forward for the next version then. Thanks for updating this as well.

**Comment by XWolfOverride** [comment] 2021-02-20 18:44
A New version is uploaded with binding options please, test from sources.

**Closed as completed** 2021-02-20 18:43 UTC

**Comment by Buster14** [comment] 2021-03-03 00:26
Hi, your app is now detected as zpevdo.b by windows defender.
Odd probably a false positive?
Also any chance you could compile the latest version ? I barely know coding and i'm afraid i might not compile it correctly

**Comment by XWolfOverride** [comment] 2021-03-03 12:41
Hi I use Windows 8.1 with Windows defender active, I updated it manually and make a quick and full scan without any found, not even my DuckDNS.exe versions. I don't know if can be a false positive or something that happened in the path between my computer to yours.

For the binary version, as I can not test the NIC binding I prefer to make a release when the changes are tested.
you can download the preview version here: http://xwolf.es/share/DuckDNS.exe

Please update me if works or not.

**Comment by Buster14** [comment] 2021-03-03 13:11
Update of DuckDNS failed, check token and domain: nullreferenceexception:Object reference not set to an instance of duckdns

Double check it and i'm sure my token is correct.
On the bright side, defender not throwing virus  alert for this..
But where is the option to select NIC btw?

**Comment by XWolfOverride** [comment] 2021-03-03 16:06
For NIC/IP binding go to advanced settings (in the gear button) use multidomain mode (if you use only one domain does not matters, use multidomain) and double click the domain.

![Binding setup](https://user-images.githubusercontent.com/7501291/109834692-c0d80380-7c42-11eb-836a-aaf35d78192b.png)

For the error, can you show me the full information about it? I'm not able to replicate

**Comment by Buster14** [comment] 2021-03-04 07:00
Hi, seems to work now, odd. Maybe yesterday duckdns was down or  i havent set ip binding..
About the ip binding, i can only test it when my server reboots, cause it's a 24/7 production server. Will let you know once it happens. Thanks

**Comment by XWolfOverride** [comment] 2021-03-04 10:27
Ok, thanks I will make test and simulate conection problems
